# Uncomment this line to define a global platform for your project
# platform :ios, '8.0'

target 'YourDay' do

pod 'SWRevealViewController', '~> 2.3'
pod 'Forecastr', '~> 0.2'

end

target 'YourDayTests' do

end

